project:
  type: website
  # pre-render: static/python/generate_music_list.py
  # resources:
  #   - static/javascript/
  #   - static/json/
  #   - static/python/
  #   - static/music/

website:
  favicon: static/images/favicon.ico
  title: "Gage Rowden"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: useful_links.qmd
        text: Useful Links
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications

# format:
#   html:
    # theme: quartz
    # css: [static/css/main.css, https://unpkg.com/98.css]
    # include-in-header:
      # text: <script type="module" src="main.js" defer></script>
          # <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          # <script src="https://cdn.jsdelivr.net/npm/p5@1.11.11/lib/p5.min.js" defer></script>
          # <link rel="stylesheet" href="https://pyscript.net/releases/2025.11.2/core.css">
          # <script type="module" src="https://pyscript.net/releases/2025.11.2/core.js"></script>

# execute:
#   cache: true
  