# Generated by Django 5.2.5 on 2025-08-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
