# Generated by Django 5.2.5 on 2025-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_authors_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ascii_image',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
