# Generated by Django 5.2 on 2025-08-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_ascii_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.URLField(),
        ),
    ]
